name: Go Unit Tests for ETL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  go-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # Change to the ETL directory
      - name: Change directory to ETL
        working-directory: ./ETL
        run: |
          echo "Changed working directory to ETL"

      # Install dependencies
      - name: Install dependencies
        working-directory: ./ETL
        run: go mod tidy

      # Run tests in ETL directory
      - name: Run tests
        working-directory: ./ETL
        run: go test -coverprofile=coverage-etl.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: etl-coverage-report
          path: ./ETL/coverage-etl.out

    # Change to the API directory
      - name: Change directory to API
        working-directory: ./API
        run: |
          echo "Changed working directory to API"

      # Install dependencies
      - name: Install dependencies
        working-directory: ./API
        run: go mod tidy

      # Run tests in ETL directory
      - name: Run tests
        working-directory: ./API
        run: go test -coverprofile=coverage-api.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage-report
          path: ./API/coverage-api.out
      
