name: Go Unit Tests for ETL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # Change to the ETL directory
      - name: Change directory to ETL
        working-directory: ./ETL
        run: |
          echo "Changed working directory to ETL"

      # Install dependencies
      - name: Install dependencies
        working-directory: ./ETL
        run: go mod tidy

      # Run tests in ETL directory
      - name: Run tests
        working-directory: ./ETL
        run: go test -coverprofile=coverage.out -json > test-report.json ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./ETL/coverage.out
      
